// <auto-generated />
using System;
using CocktailsConsole;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CocktailsConsole.Migrations
{
    [DbContext(typeof(CocktailContext))]
    [Migration("20210824100222_addingThingsToContextlol")]
    partial class addingThingsToContextlol
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CocktailsConsole.AlcoholAndAmount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AlcoholBrandAlcBrandId")
                        .HasColumnType("int");

                    b.Property<string>("Amount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CocktailId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlcoholBrandAlcBrandId");

                    b.HasIndex("CocktailId");

                    b.ToTable("AlcoholAndAmount");
                });

            modelBuilder.Entity("CocktailsConsole.AlcoholBrand", b =>
                {
                    b.Property<int>("AlcBrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AlcBrandId");

                    b.ToTable("Alcohols");
                });

            modelBuilder.Entity("CocktailsConsole.Cocktail", b =>
                {
                    b.Property<int>("CocktailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CocktailId");

                    b.ToTable("Cocktail");
                });

            modelBuilder.Entity("CocktailsConsole.IngredientAndAmount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Amount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CocktailId")
                        .HasColumnType("int");

                    b.Property<int?>("IngredientBrandIngBrandId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CocktailId");

                    b.HasIndex("IngredientBrandIngBrandId");

                    b.ToTable("IngredientAndAmount");
                });

            modelBuilder.Entity("CocktailsConsole.IngredientBrand", b =>
                {
                    b.Property<int>("IngBrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IngBrandId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("CocktailsConsole.AlcoholAndAmount", b =>
                {
                    b.HasOne("CocktailsConsole.AlcoholBrand", "AlcoholBrand")
                        .WithMany()
                        .HasForeignKey("AlcoholBrandAlcBrandId");

                    b.HasOne("CocktailsConsole.Cocktail", null)
                        .WithMany("AlcoholBrand")
                        .HasForeignKey("CocktailId");

                    b.Navigation("AlcoholBrand");
                });

            modelBuilder.Entity("CocktailsConsole.IngredientAndAmount", b =>
                {
                    b.HasOne("CocktailsConsole.Cocktail", null)
                        .WithMany("IngredientBrand")
                        .HasForeignKey("CocktailId");

                    b.HasOne("CocktailsConsole.IngredientBrand", "IngredientBrand")
                        .WithMany()
                        .HasForeignKey("IngredientBrandIngBrandId");

                    b.Navigation("IngredientBrand");
                });

            modelBuilder.Entity("CocktailsConsole.Cocktail", b =>
                {
                    b.Navigation("AlcoholBrand");

                    b.Navigation("IngredientBrand");
                });
#pragma warning restore 612, 618
        }
    }
}
